"""
geometry: SO(3), SE(3), pinhole camera
"""
from __future__ import annotations
import collections.abc
import numpy
import numpy.typing
import typing
__all__: list[str] = ['Edge', 'FactorGraph', 'KabschFit', 'PinholeCamera', 'PoseSE3', 'RansacFit', 'RotationSO3', 'Vertex', 'eight_point_algorithm', 'farthest_point_sample', 'hat', 'kabsch_algorithm', 'kabsch_ransac', 'set_seed', 'vee']
class Edge:
    @property
    def from_index(self) -> int:
        ...
    @property
    def info_matrix(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[6, 6]"]:
        ...
    @property
    def measured_pose(self) -> PoseSE3:
        ...
    @property
    def to_index(self) -> int:
        ...
class FactorGraph:
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, path_to_g2o_file: os.PathLike | str | bytes) -> None:
        ...
    @typing.overload
    def __init__(self, poses: collections.abc.Sequence[typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[4, 4]"]], timestamps: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex], edge_from: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex], edge_to: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex], measurements: collections.abc.Sequence[typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[4, 4]"]], information: collections.abc.Sequence[typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[6, 6]"]]) -> None:
        ...
    def __len__(self) -> int:
        ...
    def __repr__(self) -> str:
        ...
    def add_edge(self, from_index: typing.SupportsInt | typing.SupportsIndex, to_index: typing.SupportsInt | typing.SupportsIndex, measurement: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[4, 4]"], information: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[6, 6]"]) -> None:
        ...
    def add_vertex(self, pose: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[4, 4]"], timestamp: typing.SupportsFloat | typing.SupportsIndex = 0.0) -> int:
        """
        Append a vertex, returning the INDEX that edge endpoints use.
        """
    def gauss_newton(self, iter_threshold: typing.SupportsFloat | typing.SupportsIndex = 9.999999974752427e-07, verbose: bool = False, huber: typing.SupportsFloat | typing.SupportsIndex = False) -> None:
        ...
    def poses(self) -> list[typing.Annotated[numpy.typing.NDArray[numpy.float64], "[4, 4]"]]:
        ...
    def save_to_file(self, path_to_g2o_file: os.PathLike | str | bytes) -> None:
        ...
    def set_information(self, information: collections.abc.Sequence[typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[6, 6]"]]) -> None:
        ...
    def set_poses(self, poses: collections.abc.Sequence[typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[4, 4]"]]) -> None:
        ...
    @property
    def edges(self) -> list[Edge]:
        ...
    @property
    def vertices(self) -> list[Vertex]:
        ...
class KabschFit:
    @property
    def T_ji(self) -> PoseSE3:
        ...
    @property
    def degeneracy(self) -> float:
        ...
class PinholeCamera:
    @typing.overload
    def __init__(self, fx: typing.SupportsFloat | typing.SupportsIndex, fy: typing.SupportsFloat | typing.SupportsIndex, cx: typing.SupportsFloat | typing.SupportsIndex, cy: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @typing.overload
    def __init__(self, K: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 3]"]) -> None:
        ...
    @typing.overload
    def back_project(self, pixel: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[2, 1]"], depth: typing.SupportsFloat | typing.SupportsIndex) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
        ...
    @typing.overload
    def back_project(self, pixels: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 2]", "flags.f_contiguous"], depth: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 3]"]:
        ...
    def matrix(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 3]"]:
        ...
    def project(self, point: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[2, 1]"]:
        ...
    @property
    def cx(self) -> float:
        ...
    @property
    def cy(self) -> float:
        ...
    @property
    def fx(self) -> float:
        ...
    @property
    def fy(self) -> float:
        ...
class PoseSE3:
    @staticmethod
    def exp(tangent: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[6, 1]"]) -> PoseSE3:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, T: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[4, 4]"]) -> None:
        ...
    @typing.overload
    def __init__(self, R: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 3]"], t: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"]) -> None:
        ...
    @typing.overload
    def __mul__(self, arg0: PoseSE3) -> PoseSE3:
        ...
    @typing.overload
    def __mul__(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
        ...
    def adjoint(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[6, 6]"]:
        ...
    def inverse(self) -> PoseSE3:
        ...
    def log(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[6, 1]"]:
        ...
    def matrix(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[4, 4]"]:
        ...
    def rotation(self) -> RotationSO3:
        ...
    def translation(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
        ...
class RansacFit:
    def __init__(self, T_ji: PoseSE3, inliers: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex], inlier_ratio: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    def __repr__(self) -> str:
        ...
    @property
    def T_ji(self) -> PoseSE3:
        ...
    @property
    def inlier_ratio(self) -> float:
        ...
    @property
    def inliers(self) -> list[int]:
        ...
class RotationSO3:
    @staticmethod
    def exp(omega: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"]) -> RotationSO3:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, R: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 3]"]) -> None:
        ...
    @typing.overload
    def __mul__(self, arg0: RotationSO3) -> RotationSO3:
        ...
    @typing.overload
    def __mul__(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
        ...
    def __repr__(self) -> str:
        ...
    def inverse(self) -> RotationSO3:
        ...
    def log(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
        ...
    def matrix(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 3]"]:
        ...
class Vertex:
    @property
    def pose(self) -> PoseSE3:
        ...
    @property
    def timestamp(self) -> float:
        ...
def eight_point_algorithm(ray_i: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 3]"], ray_j: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 3]"]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 3]"]:
    ...
def farthest_point_sample(points: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 3]"], num_points_to_sample: typing.SupportsInt | typing.SupportsIndex) -> list[int]:
    ...
def hat(w: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 3]"]:
    ...
def kabsch_algorithm(point_i: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 3]"], point_j: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 3]"]) -> KabschFit:
    ...
def kabsch_ransac(point_i: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 3]"], point_j: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 3]"], inlier_threshold: typing.SupportsFloat | typing.SupportsIndex = 0.05, degeneracy_threshold: typing.SupportsFloat | typing.SupportsIndex = 0.001) -> RansacFit:
    ...
def set_seed(seed: typing.SupportsInt | typing.SupportsIndex) -> None:
    ...
def vee(W: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 3]"]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
    ...
