"""
geometry: SO(3), SE(3), pinhole camera
"""
from __future__ import annotations
import numpy
import numpy.typing
import typing
__all__: list[str] = ['PinholeCamera', 'PoseSE3', 'RotationSO3', 'eight_point_algorithm', 'hat', 'vee']
class PinholeCamera:
    @typing.overload
    def __init__(self, fx: typing.SupportsFloat | typing.SupportsIndex, fy: typing.SupportsFloat | typing.SupportsIndex, cx: typing.SupportsFloat | typing.SupportsIndex, cy: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @typing.overload
    def __init__(self, K: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 3]"]) -> None:
        ...
    def back_project(self, pixel: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[2, 1]"], depth: typing.SupportsFloat | typing.SupportsIndex) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
        ...
    def matrix(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 3]"]:
        ...
    def project(self, point: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[2, 1]"]:
        ...
    @property
    def cx(self) -> float:
        ...
    @property
    def cy(self) -> float:
        ...
    @property
    def fx(self) -> float:
        ...
    @property
    def fy(self) -> float:
        ...
class PoseSE3:
    @staticmethod
    def exp(tangent: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[6, 1]"]) -> PoseSE3:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, T: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[4, 4]"]) -> None:
        ...
    @typing.overload
    def __init__(self, R: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 3]"], t: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"]) -> None:
        ...
    @typing.overload
    def __mul__(self, arg0: PoseSE3) -> PoseSE3:
        ...
    @typing.overload
    def __mul__(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
        ...
    def adjoint(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[6, 6]"]:
        ...
    def inverse(self) -> PoseSE3:
        ...
    def log(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[6, 1]"]:
        ...
    def matrix(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[4, 4]"]:
        ...
    def rotation(self) -> RotationSO3:
        ...
    def translation(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
        ...
class RotationSO3:
    @staticmethod
    def exp(omega: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"]) -> RotationSO3:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, R: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 3]"]) -> None:
        ...
    @typing.overload
    def __mul__(self, arg0: RotationSO3) -> RotationSO3:
        ...
    @typing.overload
    def __mul__(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
        ...
    def __repr__(self) -> str:
        ...
    def inverse(self) -> RotationSO3:
        ...
    def log(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
        ...
    def matrix(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 3]"]:
        ...
def eight_point_algorithm(ray_i: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 3]"], ray_j: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 3]"]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 3]"]:
    ...
def hat(w: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 3]"]:
    ...
def vee(W: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 3]"]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
    ...
